# vim: syntax=yaml ts=2 sts=2 sw=2 expandtab
name: geofront
services:
  subsonic:
    tty: true
    image: skaven/subsonic:6.1.6-2
    volumes:
    - /raid/subsonic/subsonic-data:/subsonic
    - /raid/MP3s:/music/MP3s:ro
    - /raid/Alans Music:/music/Alan:ro
    - /raid/Magers Music:/music/Magers:ro
    - /raid/user/lori/My Documents/My Music:/music/Lori:ro
    - /raid/subsonic/playlists:/playlists
    - /raid/subsonic/video:/video
    stdin_open: true
    restart: unless-stopped

  nginx:
    ports:
    - 80:80/tcp
    - 443:443/tcp
    tty: true
    image: skaven/nginx:20250113
    volumes:
    - /raid/letsencrypt:/etc/letsencrypt
    - /raid/www:/usr/share/nginx/html:ro
    restart: unless-stopped
    links:
    - subsonic
    - php
    - zoneminder

  php:
    image: skaven/php:20231119
    volumes:
    - /raid/www:/usr/share/nginx/html:ro
    - /raid/www/photos:/usr/share/nginx/html/photos
    - /raid/photo_gallery_cache:/_sfpg_data
    - /raid/user/lori/My Documents/My Pictures:/photo_root/lori:ro
    - /raid/user/skaven/Photos:/photo_root/paul:ro
    restart: unless-stopped

  plex:
    network_mode: host
    hostname: plex
    tty: true
    image: skaven/plex:1.18.1.1973
    volumes:
    - /raid/plex:/config
    - /raid/Video:/data:ro
    - /raid/user/lori/My Documents/My Pictures:/photos:ro
    - /raid/MP3s:/music:ro
    stdin_open: true
    restart: unless-stopped

  samba:
    tty: true
    command:
    - -n
    - -l
    - -u skaven;skaven;1000
    - -u lori;lori;500
    - -s raid;/raid6;yes;no;no;all;none
    - -m
    image: skaven/samba:2020.09
    pull_policy: missing
    volumes:
    - /raid:/raid6
    - /raid:/raid
    - /raid/user:/home
    stdin_open: true
    network_mode: host
    restart: unless-stopped

  zm-mariadb:
    image: mariadb:11.6
    pull_policy: missing
    environment:
      MARIADB_ROOT_PASSWORD: flargle
    expose:
    - "3306"
    volumes:
    - /raid/zoneminder/mariadb:/var/lib/mysql:Z
  zoneminder:
    image: skaven/zoneminder:1.36.35-2
    pull_policy: missing
    links:
    - zm-mariadb:mariadb
    volumes:
    - /raid/zoneminder/events:/var/cache/zoneminder/events
    - /raid/zoneminder/images:/var/cache/zoneminder/images
    - /raid/zoneminder/temp:/var/cache/zoneminder/temp
    - /raid/zoneminder/logs/zoneminder:/var/log/zoneminder
    - /raid/zoneminder/logs/apache2:/var/log/apache2
