subsonic:
  ports:
  - 4040:4040/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: skaven/subsonic:6.1.3
  volumes:
  - /raid/subsonic/subsonic-data:/subsonic
  - /raid/MP3s:/music/MP3s:ro
  - /raid/Alans Music:/music/Alan:ro
  - /raid/user/lori/My Documents/My Music:/music/Lori:ro
  - /raid/subsonic/playlists:/playlists
  - /raid/subsonic/video:/video
  stdin_open: true
  restart: unless-stopped

apache:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: skaven/apache-php:latest
  volumes:
  - /raid/www-logs:/var/log/apache2
  - /raid/www:/var/www/html:ro
  - /raid/user:/home:ro
  stdin_open: true
  net: host
  restart: unless-stopped

plex:
  ports:
  - 32400:32400/tcp
  - 32410:32410/udp
  - 32412:32412/udp
  - 32413:32413/udp
  - 32414:32414/udp
  - 1900:1900/udp
  - 32469:32469/tcp
  - 5353:5353/udp
  net: host
  hostname: plex
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: plex
  image: skaven/plex:1.9.3.4290
  volumes:
  - /raid/plex:/config
  - /raid/Video:/data:ro
  - /raid/user/lori/My Documents/My Pictures:/photos:ro
  - /raid/MP3s:/music:ro
  stdin_open: true
  restart: unless-stopped

crashplan:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: docker-crashplan
  image: skaven/crashplan:pro6.7.2
  volumes:
  - /raid/crashplan-conf/conf:/opt/crashplan/conf
  - /raid/crashplan-conf/cache:/opt/crashplan/cache
  - /raid/crashplan-conf/var:/var/lib/crashplan
  - /raid/crashplan-store:/crashplan-store
  - /raid:/raid5:ro
  - /:/geofront-root:ro
  stdin_open: true
  restart: unless-stopped

samba:
  ports:
  - 139:139
  - 445:445
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - -n
  - -l
  - -u skaven;skaven;1000
  - -u lori;lori;500
  - -s raid;/raid6;yes;no;no;all;none
  - -m
  image: skaven/samba:latest
  volumes:
  - /raid:/raid6
  - /raid:/raid
  - /raid/user:/home
  stdin_open: true
  net: host
  restart: unless-stopped

