subsonic:
  ports:
  - 4040:4040/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: skaven/subsonic:latest
  cpu_shares: 512
  volumes:
  - /raid/subsonic/subsonic-data:/subsonic
  - /raid/MP3s:/music/MP3s:ro
  - /raid/Alans\ Music:/music/Alan:ro
  - /raid/user/lori/My\ Documents/My\ Music:/music/lori:ro
  - /raid/subsonic/playlists:/playlists
  - /raid/subsonic/video:/video
  stdin_open: true

apache:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: skaven/apache-php:latest
  cpu_shares: 256
  volumes:
  - /raid/www:/var/www/html:ro
  - /raid/user:/home:ro
  - /raid/www-logs:/var/log/apache2
  stdin_open: true

plex:
  ports:
  - 32400:32400/tcp
  - 32410:32410/udp
  - 32412:32412/udp
  - 32413:32413/udp
  - 32414:32414/udp
  - 1900:1900/udp
  - 32469:32469/tcp
  - 5353:5353/udp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: plex
  image: skaven/plex:1.1.4.2757
  cpu_shares: 1024
  volumes:
  - /raid/plex:/config
  - /raid/Video:/data:ro
  stdin_open: true
  net: bridge

crashplan:
  ports:
  - 4242:4242/tcp
  - 4343:4343/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: docker-crashplan
  image: skaven/crashplan:4.8
  cpu_shares: 512
  volumes:
  - /raid/crashplan-conf/conf:/opt/crashplan/conf
  - /raid/crashplan-conf/cache:/opt/crashplan/cache
  - /raid/crashplan-conf/var:/var/lib/crashplan
  - /raid/crashplan-store:/crashplan-store
  - /raid:/raid5:ro
  - /:/geofront-root:ro
  stdin_open: true
  net: host

dnsmasq:
  ports:
  - 53:53/tcp
  - 53:53/udp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - --log-facility=-
  - --conf-file=/dnsmasq/dnsmasq.conf
  image: andyshinn/dnsmasq:latest
  volumes:
  - /raid/dnsmasq:/dnsmasq
  stdin_open: true
  net: host
  cap_add:
  - NET_ADMIN

samba:
  ports:
  - 139:139
  - 445:445
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - -n
  - -u skaven;skaven;1000
  - -u lori;lori;500
  - -s raid;/raid6;yes;no;no;all;none
  - -m
  image: skaven/samba:latest
  volumes:
  - /raid:/raid6
  - /raid/user:/home
  stdin_open: true
  net: host

