subsonic:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: skaven/subsonic:6.1.5
  volumes:
  - /raid/subsonic/subsonic-data:/subsonic
  - /raid/MP3s:/music/MP3s:ro
  - /raid/Alans Music:/music/Alan:ro
  - /raid/user/lori/My Documents/My Music:/music/Lori:ro
  - /raid/subsonic/playlists:/playlists
  - /raid/subsonic/video:/video
  stdin_open: true
  restart: unless-stopped

nginx:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  tty: true
  image: skaven/nginx:20190705
  volumes:
  - /raid/letsencrypt:/etc/letsencrypt
  - /raid/www:/usr/share/nginx/html:ro
  restart: unless-stopped
  links:
  - subsonic
  - php
  - web-frontdoor
  - web-backyard
  - web-garage

php:
  image: skaven/php:20181230
  volumes:
  - /raid/www:/usr/share/nginx/html:ro
  - /raid/www/photos:/usr/share/nginx/html/photos
  - /raid/photo_gallery_cache:/_sfpg_data
  - /raid/user/lori/My Documents/My Pictures:/photo_root/lori:ro
  - /raid/user/skaven/Photos:/photo_root/paul:ro
  restart: unless-stopped

plex:
  ports:
  - 32400:32400/tcp
  - 32410:32410/udp
  - 32412:32412/udp
  - 32413:32413/udp
  - 32414:32414/udp
  - 1900:1900/udp
  - 32469:32469/tcp
  - 5353:5353/udp
  net: host
  hostname: plex
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: plex
  image: skaven/plex:1.14.1.5488
  volumes:
  - /raid/plex:/config
  - /raid/Video:/data:ro
  - /raid/user/lori/My Documents/My Pictures:/photos:ro
  - /raid/MP3s:/music:ro
  stdin_open: true
  restart: unless-stopped

crashplan:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: docker-crashplan
  image: skaven/crashplan:pro6.9.2-759
  volumes:
  - /raid/crashplan-conf/conf:/opt/crashplan/conf
  - /raid/crashplan-conf/cache:/opt/crashplan/cache
  - /raid/crashplan-conf/metadata:/opt/crashplan/metadata
  - /raid/crashplan-conf/logs:/opt/crashplan/log
  - /raid/crashplan-conf/var:/var/lib/crashplan
  - /raid/crashplan-conf/root:/root
  - /raid/crashplan-store:/crashplan-store
  - /raid:/raid5:ro
  - /:/geofront-root:ro
  ports:
  - 5900:5900
  stdin_open: true
  restart: unless-stopped

samba:
  ports:
  - 139:139
  - 445:445
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - -n
  - -l
  - -u skaven;skaven;1000
  - -u lori;lori;500
  - -s raid;/raid6;yes;no;no;all;none
  - -m
  image: skaven/samba:2018.11
  volumes:
  - /raid:/raid6
  - /raid:/raid
  - /raid/user:/home
  stdin_open: true
  net: host
  restart: unless-stopped

machinery-frontdoor:
  image: kerberos/machinery:v2.5.1
  expose:
  - 8889
  volumes:
  - /raid/kerberos/40-frontdoor/capture:/etc/opt/kerberosio/capture
  - /raid/kerberos/40-frontdoor/config:/etc/opt/kerberosio/config
  - /raid/kerberos/40-frontdoor/logs:/etc/opt/kerberosio/logs
  restart: unless-stopped
web-frontdoor:
  image: kerberos/web:v2.5.1
  environment:
  - KERBEROSIO_SECURE_SSL=true
  volumes_from:
  - machinery-frontdoor
  volumes:
  - /raid/kerberos/webconfig:/var/www/web/config
  links:
  - machinery-frontdoor:machinery
  restart: unless-stopped

machinery-backyard:
  image: kerberos/machinery:v2.5.1
  expose:
  - 8889
  volumes:
  - /raid/kerberos/41-backyard/capture:/etc/opt/kerberosio/capture
  - /raid/kerberos/41-backyard/config:/etc/opt/kerberosio/config
  - /raid/kerberos/41-backyard/logs:/etc/opt/kerberosio/logs
  restart: unless-stopped
web-backyard:
  image: kerberos/web:v2.5.1
  environment:
  - KERBEROSIO_SECURE_SSL=true
  volumes_from:
  - machinery-backyard
  volumes:
  - /raid/kerberos/webconfig:/var/www/web/config
  links:
  - machinery-backyard:machinery
  restart: unless-stopped

machinery-garage:
  image: kerberos/machinery:v2.5.1
  expose:
  - 8889
  volumes:
  - /raid/kerberos/42-garage/capture:/etc/opt/kerberosio/capture
  - /raid/kerberos/42-garage/config:/etc/opt/kerberosio/config
  - /raid/kerberos/42-garage/logs:/etc/opt/kerberosio/logs
  restart: unless-stopped
web-garage:
  image: kerberos/web:v2.5.1
  environment:
  - KERBEROSIO_SECURE_SSL=true
  volumes_from:
  - machinery-garage
  volumes:
  - /raid/kerberos/webconfig:/var/www/web/config
  links:
  - machinery-garage:machinery
  restart: unless-stopped
